// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-9RAx-P-GFBz8CzJt74PLv_cVndfqn7c',
    appId: '1:91651925903:web:703bab7e217c49d9db8dfa',
    messagingSenderId: '91651925903',
    projectId: 'udharcard-app',
    authDomain: 'udharcard-app.firebaseapp.com',
    storageBucket: 'udharcard-app.firebasestorage.app',
    measurementId: 'G-EDEF2VE8LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_CrlNjXE1YhLBvOe66p2FfT35Mobz3P8',
    appId: '1:91651925903:android:3c0ca3eb6de91eafdb8dfa',
    messagingSenderId: '91651925903',
    projectId: 'udharcard-app',
    storageBucket: 'udharcard-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXCHfPyAOgrfj3qtxvXq3BEG9j3_Q6CZs',
    appId: '1:91651925903:ios:0bead75cde4bab14db8dfa',
    messagingSenderId: '91651925903',
    projectId: 'udharcard-app',
    storageBucket: 'udharcard-app.firebasestorage.app',
    iosBundleId: 'com.udharcard.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXCHfPyAOgrfj3qtxvXq3BEG9j3_Q6CZs',
    appId: '1:91651925903:ios:b3b0d7b63332283cdb8dfa',
    messagingSenderId: '91651925903',
    projectId: 'udharcard-app',
    storageBucket: 'udharcard-app.firebasestorage.app',
    iosBundleId: 'com.example.wise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-9RAx-P-GFBz8CzJt74PLv_cVndfqn7c',
    appId: '1:91651925903:web:bacacf31b0dab2b0db8dfa',
    messagingSenderId: '91651925903',
    projectId: 'udharcard-app',
    authDomain: 'udharcard-app.firebaseapp.com',
    storageBucket: 'udharcard-app.firebasestorage.app',
    measurementId: 'G-FLLSFP6R13',
  );
}
